apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: LoadBalancer  # or ClusterIP if only internal
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    app: backend

