- name: Setup backend container
  block:
    - name: Create app-net Docker network
      docker_network:
        name: app-net
        state: present

    - name: Pull image from repository
      docker_image:
        name: brianbwire/brian-yolo-backend:v1.0.0
        source: pull

    - name: Create Node.js Backend Container
      docker_container:
        name: brian-yolo-backend
        image: brianbwire/brian-yolo-backend:v1.0.0
        networks:
          - name: app-net
        ports:
          - "5000:5000"
        command: "npm start"
      become: yes
  tags: backend
