- name: Run mongodb container
  docker_container:
    name: mongodb
    image: mongo:4.4
    ports:
      - "27017:27017"
    env:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example